---
title: "West Coast spatial plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load data and packages, cache=F, message = FALSE}
library(broom)
library(tidyverse)
library(ggforce) 
library(gridExtra)
library(geosphere)
library(viridis)
library(janitor)

#CGI calculated on linux server because my computer can't handle that much data
#Visualizations run locally because some packages have issues on linux
load("wc_cgi.rda")
load("wc_gic.rda")

#Also load the haul-level data
load("bt_dat_ret.rda")

wc_cgi <-wc_cgi %>% 
  mutate(disp_species = ifelse(disp_species == "Pacific\nHake","Shoreside\nHake", disp_species))

wc_gic <- wc_gic %>% 
  mutate(disp_species = ifelse(disp_species == "Pacific\nHake","Shoreside\nHake", disp_species))

bt_dat <- bt_dat %>% 
  mutate(disp_species = gsub(" ", "\n", species),
         disp_species = ifelse(disp_species == "Pacific\nHake","Shoreside\nHake", disp_species)) 
  

#Cropped N. America polygon for plotting
load("n_america_clip.rda")

```

```{r COG point plot, cache=F, message = FALSE, fig.width=10, fig.height=10, fig.cap="\\label{fig:figs}Figure 1. Center of gravity of all retained species, all discarded species, and selected retained species, 2002-2018."}
#Plot COG as points
library(tidyverse)
wc_cgi %>%
  dplyr::select(year,disp_species,xcg,ycg) %>%
  distinct() %>%
  ggplot() +
  #geom_polygon(data = n_america_clip, aes(x=long, y = lat, group = group),fill="lightgray") +
  geom_point(aes(xcg,ycg,color=year)) +
  scale_color_viridis()+
  #coord_map(xlim = c(-125.5,-122),ylim = c(37.25, 48))+
  facet_wrap(~disp_species, scales="free")+
  #theme(strip.text = element_text(size = 8))+
  theme_bw()

```

```{r lat COG, cache=F, message = FALSE, fig.width=10, fig.height=10, fig.cap="\\label{fig:figs}Figure 2. Latitudinal center of gravity of all retained species, all discarded species, and selected retained species, 2002-2018."}

#Plot lat CG and lon CG over time
wc_cgi %>%
  ggplot(aes(x = year, y = ycg))+
  geom_line()+
  facet_wrap(~disp_species, scales="free")+
  theme_bw()+
  theme(strip.text = element_text(size = 8))

```


```{r long COG, cache=F, message = FALSE, fig.width=10, fig.height=10, fig.cap="\\label{fig:figs}Figure 3. Longitudinal center of gravity of all retained species, all discarded species, and selected retained species, 2002-2018."}

wc_cgi %>%
  ggplot(aes(x = year, y = xcg))+
  geom_line()+
  facet_wrap(~disp_species, scales = "free")+
  theme_bw()+
  theme(strip.text = element_text(size = 8))

```

```{r ellipses, cache=F, message = FALSE, fig.width=10, fig.height=10, fig.cap="\\label{fig:figs}Figure 4. Ellipse plots showing center of gravity and inertia, 2002-2018."}

mycgifun2 <- function(mycgi){
  return(bind_cols(mycgi %>% 
                     dplyr::select(disp_species,year,xaxe1,xaxe2) %>% 
                     gather(xaxis,xval,-c(year, disp_species)) %>% 
                     dplyr::select(-xaxis),
                   mycgi %>% dplyr::select(disp_species,year,yaxe1,yaxe2) %>% 
                     gather(yaxis,yval,-year,-disp_species) %>% 
                     dplyr::select(-yaxis,-year,-disp_species)))
}

mycgifun2(wc_cgi) %>% 
  filter(!is.nan(xval)) %>% 
  ggplot() +
  #geom_polygon(data = n_america_clip, aes(x=long, y = lat, group = group),fill="lightgray") +
  geom_mark_ellipse(aes(xval,yval,fill=factor(year)),expand = unit(0, "mm"),alpha=0.12) +
  scale_fill_viridis(discrete=TRUE)+
  facet_wrap(~disp_species, scales="free")+
 #coord_map(xlim = c(-126.5,-121.75),ylim = c(36.5, 49))+
  theme_bw()
  NULL

```

```{r GIC, cache=F, message = FALSE, fig.width=10, fig.height=10, fig.cap="\\label{fig:figs}Figure 5. Global index of colocation, 2002-2018."}


wc_gic %>%  
  ggplot() +
  geom_line(aes(x = year, y = gic))+
  facet_wrap(~disp_species)+
 #coord_map(xlim = c(-126.5,-121.75),ylim = c(36.5, 49))+
  theme_bw()



```

```{r distance from port, cache=F, message = FALSE, fig.width=10, fig.height=10, fig.cap="\\label{fig:figs}Figure 6. Mean distance between haul location and return port (usually equivalent to landing port), 2002-2018."}


bt_dat %>% 
  filter(species!="all_discard") %>% 
  group_by(disp_species, year) %>% 
  summarise(mean_dist_km = mean(dist_km, na.rm=T)) %>% 
  ggplot()+
  geom_line(aes(x = year, y = mean_dist_km))+
  facet_wrap(~disp_species, scales= "free")



```


